### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by udayzee05** [geaxgx/openvino_hand_tracker#2]
(E:\R&D\openvino_hand_tracker\venv) PS E:\R&D\openvino_hand_tracker> python .\HandTracker.py
896 anchors have been created
Loading Inference Engine
Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
Palm Detection model - Reading network files:
        models/palm_detection_FP32.xml
        models/palm_detection_FP32.bin
Input blob: input - shape: [1, 3, 128, 128]
Output blob: classificators - shape: [1, 896, 1]
Output blob: regressors - shape: [1, 896, 18]
Loading palm detection model into the plugin
Landmark model - Reading network files:
        models/hand_landmark_FP32.xml
        models/hand_landmark_FP32.bin
Input blob: input_1 - shape: [1, 3, 224, 224]
Output blob: Identity_1 - shape: [1, 1]
Output blob: Identity_2 - shape: [1, 1]
Output blob: Identity_dense/BiasAdd/Add - shape: [1, 63]
Loading landmark model to the plugin
E:\R&D\openvino_hand_tracker\mediapipe_utils.py:141: RuntimeWarning: overflow encountered in exp
  scores = 1 / (1 + np.exp(-scores))
Traceback (most recent call last):
  File ".\HandTracker.py", line 417, in <module>
    ht.run()
  File ".\HandTracker.py", line 338, in run
    self.pd_postprocess(inference)
  File ".\HandTracker.py", line 149, in pd_postprocess
    self.regions = mpu.non_max_suppression(self.regions, self.pd_nms_thresh)
  File "E:\R&D\openvino_hand_tracker\mediapipe_utils.py", line 188, in non_max_suppression
    return [regions[i[0]] for i in indices]
  File "E:\R&D\openvino_hand_tracker\mediapipe_utils.py", line 188, in <listcomp>
    return [regions[i[0]] for i in indices]
IndexError: invalid index to scalar variable.

**Comment by geaxgx** [comment]
My guess is that the error comes from a change of behavior of the function cv2.dnn.NMSBoxes().
What is your version of opencv  ?
Can you try to modify the line:
https://github.com/geaxgx/openvino_hand_tracker/blob/06703fa935b71a57fc21df54f804cd9878bcae10/mediapipe_utils.py#L188
replacing it by:
`    return [regions[i] for i in indices]`

**Comment by udayzee05** [comment]
Worked. Thank You, I think you should add requirement .txt file


certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
numpy==1.23.3
opencv-python==4.7.0.68
openvino==2021.2
tbb==2020.3.254
wincertstore==0.2
